---
userSwapChoices:
    - none
    - file

initialPartitioningChoice: none
initialSwapChoice: file

drawNestedPartitions: true
alwaysShowPartitionLabels: true

allowManualPartitioning: true

defaultFileSystemType: "ext4"

requiredStorage: 5.5

availableFileSystemTypes:
    - ext4
    - btrfs
    - xfs

defaultPartitionTableType: gpt

luksGeneration: luks1
