---
defaultGroups:
    - sudo
    - adm
    - cdrom
    - dip
    - plugdev
    - users
    - audio
    - video

allowWeakPasswords: false
allowWeakPasswordsDefault: false

autologinGroup: autologin

sudoGroup: sudo
