PROJECT_NAME="Niveth Linux"
PROJECT_ID="niveth"
PROJECT_VERSION="0.1"
PROJECT_ARCH="amd64"

BASE_DISTRO="ubuntu"
BASE_RELEASE="resolute"
BASE_MIRROR="http://archive.ubuntu.com/ubuntu"

DESKTOP="gnome"
INSTALLER="calamares"

ROOTFS_DIR="$PROJECT_ROOT/build/rootfs"
ISO_WORK_DIR="$PROJECT_ROOT/build/iso-work"
ISO_OUTPUT_DIR="$PROJECT_ROOT/iso"

ISO_NAME="Niveth-0.1-amd64.iso"
MAX_ISO_SIZE_MB="5120"
