# Niveth Dark

font_family Noto Mono
font_size 11.0

background_opacity 0.50
dynamic_background_opacity yes
background_blur 20

window_padding_width 14
window_margin_width 0

cursor_shape beam
cursor_blink_interval 0

enable_audio_bell no
visual_bell_duration 0.0

foreground #E7EDF4
background #182433

color0  #182433
color1  #D8797F
color2  #7FA58C
color3  #C5A66A
color4  #7F9DB8
color5  #A68EAA
color6  #76AAB2
color7  #DCE4EC

color8  #627181
color9  #E89AA0
color10 #9CBCA7
color11 #D9BF87
color12 #9AB5CD
color13 #C0A9C0
color14 #95C7CD
color15 #F7F9FC

cursor #E7EDF4
cursor_text_color #182433

selection_foreground #E7EDF4
selection_background #4E6378

linux_display_server wayland
