# Niveth Light

font_family Noto Mono
font_size 11.0

background_opacity 0.50
dynamic_background_opacity yes
background_blur 20

window_padding_width 14
window_margin_width 0

cursor_shape beam
cursor_blink_interval 0

enable_audio_bell no
visual_bell_duration 0.0

foreground #263442
background #F7F9FC

color0  #263442
color1  #B85C62
color2  #4F7A63
color3  #9A7A3A
color4  #5D7A9A
color5  #856C88
color6  #4E8791
color7  #E7ECF2

color8  #566575
color9  #D46F76
color10 #6E9B7F
color11 #B69652
color12 #7F9DB8
color13 #A58AA8
color14 #72AEB7
color15 #FFFFFF

cursor #263442
cursor_text_color #F7F9FC

selection_foreground #263442
selection_background #C9D6E2

linux_display_server wayland
